행렬 : 수나, 식을 사각형 모양으로 배열하고, 괄호로 묶어둔 것  
원소, 성분 : 행렬속 배열된 식 혹은 값  
행(Row) : 가로줄 || 열(Column) : 세로줄  
  
행렬의 일반적인 형태는  m행 n열로 구성되어있으며, *m X n 행렬* 또는 *m행 n열의 행렬* 이라고 함

정방행렬, 정사각행렬 : 행과 열의 개수가 동일한 행렬  
주대각성분 : $a_{11}, a_{22}, ... , a_{nn}$  
대각행렬 : 주대각 성분을 제외한 모든 부분이 0인 행렬  
단위행렬, 항등행렬 : 주대각성분이 1이고 나머지는 0인 행렬 일반적으로 ***E, I***라고 표시

In [27]:
import numpy as np

In [17]:
# 2*2 행렬 생성
matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

print(matrix_A.shape, matrix_B.shape)
print(matrix_A)
print(matrix_B)

(2, 2) (2, 2)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [18]:
# 3*3 대각 행렬 생성
matrix_C = np.array([[1, 0, 0],
                     [0, 2, 0],
                     [0, 0, 3]])
print(matrix_C)

# 주대각 성분 = a11, a22, a33
print(matrix_C[0][0], matrix_C[1][1], matrix_C[2][2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
1 2 3


In [22]:
# 3*3 항등 행렬 생성
matrix_E = np.array([[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]])
print(matrix_E)
# 주대각 성분 = a11, a22, a33
print(matrix_E[0][0], matrix_E[1][1], matrix_E[2][2])

[[1 0 0]
 [0 1 0]
 [0 0 1]]
1 1 1


In [24]:
# 전치 행렬
matrix_D = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

# 2*3의 matrix_D를 전치를 통해 3*2 matrix_D_t로 변형
matrix_D_t = matrix_D.T

print(matrix_D)
print(matrix_D_t)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [26]:
# 대칭 행렬 A = AT
matrix_F = np.array([[1, 2, 3],
                     [2, 4, 5],
                     [3, 5, 2]])

# 전치를 진행해도 전치 이전의 행렬과 모양과 값이 동일
matrix_F_t = matrix_F.T

print(matrix_F)
print(matrix_F_t)

[[1 2 3]
 [2 4 5]
 [3 5 2]]
[[1 2 3]
 [2 4 5]
 [3 5 2]]
