행렬의 기본 연산 : 합(덧셈), 차(뺄셈), 스칼라배, 곱  
합, 차 : 두 행렬의 크기가 동일할 떄만 적용 가능  
곱 : A행렬의 열, B행렬의 행의 개수가 동일해야 가능  
 - m X n = A, n X p = B => AB = m X p

In [1]:
import numpy as np

In [13]:
matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

matrix_C = np.array([[9, 10],
                     [11, 12],
                     [13, 14]])
# A, B는 사이즈가 동일하기 때문에 연산이 정상적으로 진행
print(matrix_A + matrix_B)
print(matrix_B + matrix_A)


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [14]:
# C는 사이즈가 다르기 때문에 연산이 진행되지 않음
# ValueError: operands could not be broadcast together with shapes (3,2) (2,2)
#  -> 행렬간의 사이즈가 일치하지않으니 broadcast도 안되더라 사이즈 맞춰라 라는 뜻
print(matrix_C + matrix_A)

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

# $$ c_{ij} = a_{i1}b_{1j} + ... + a_{in}b_{nj} = \sum\limits_{k=1}^{n} {a_{ik}b_{kj}}     (단, 1 <= i, j <= n) $$ 

In [5]:
# 스칼라배의 연산 cA 각 성분에 스칼라 c를 곱하는 것
print(3 * matrix_A)
print(3 * matrix_B)
print(3 * matrix_C)

[[ 3  6]
 [ 9 12]]
[[15 18]
 [21 24]]
[[27 30]
 [33 36]
 [39 42]]


In [10]:
matrix_D = np.array([[1, 2, 3],
                     [4, 5, 6]])

# 행렬 곱은 이렇게 그냥 곱하거나
print(matrix_A*matrix_B)

# np.dot을 활용해서 연산 진행 가능
np.dot(matrix_C, matrix_D)

[[ 5 12]
 [21 32]]


array([[ 49,  68,  87],
       [ 59,  82, 105],
       [ 69,  96, 123]])

벡터 : 행이나 열이 하나밖에 없는 행렬  
행벡터 : 행으로만 이뤄진 행렬  
열벡터 : 열로만 이뤄진 행렬  

In [12]:
vector_A = np.array([1, 2, 3])
vector_B = np.array([[1], 
                     [2], 
                     [3]])

print(vector_A)
print(vector_B)

[1 2 3]
[[1]
 [2]
 [3]]
