행렬 : $ A = [a_{ij}]_{m*n} $  
정방행렬 : 행과 열의 개수가 같은 행렬  
n차 정방행렬 : 행과 열의 개수가 n개인 행렬  
주대각 성분 : 행과 열의 번호가 같은 성분(행렬의 대각선값) $ a_{11}, a_{22}, ..., a_{nn} $  
단위행렬 : 주대각 성분이 1이고 그외 값은 모두 0인 행렬 I라고 표시함  
영행렬 : 모든 성분이 0인 행렬

In [2]:
import numpy as np

In [3]:
# 2*3 행렬
matrix_A = np.array([[1, 2, 3],
                     [3, 4, 6]])
# 2*2 행렬, 2차 정방행렬
matrix_B = np.array([[1, 2],
                     [3, 4]])

# 3*3 항등행렬
matrix_I = np.array([[1, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]])

# 3*3 영행렬, numpy.zeros로 영행렬을 쉽게 만들 수 있다
matrix_O = np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]])

matrix_O2 = np.zeros([3, 3])

print(matrix_O)
print(matrix_O2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


행렬의 합 : $ A = [a_{ij}]_{m*n} $ 과 $ B = [b_{ij}]_{m*n} $ 의 합인 행렬 $ C = [c_{ij}]_{m*n} $
 - $ c_{ij} $ 는 대응하는 성분들의 합이다. $ c_{ij} = a_{ij} + b_{ij} $
 - 서로 합하는 행렬의 크기가 다르면 연산되지않는다.

행렬의 차 : $ A = [a_{ij}]_{m*n} $ 과 $ B = [b_{ij}]_{m*n} $ 의 차인 행렬 $ C = [c_{ij}]_{m*n} $
 - $ c_{ij} $ 는 대응하는 성분들의 차다. $ c_{ij} = a_{ij} - b_{ij} $
 - $ A - B = A + (-1)B $ 
 - 서로 빼는 행렬의 크기가 다르면 연산되지않는다.

행렬의 스칼라배 : $ A = [a_{ij}]_{m*n} $ 행렬에 스칼라 k를 곱하는것 $ kA = [ka_{ij}]_{m*n} $ 이므로 A의 각 성분을 k배 한것
 - 스칼라배는 행렬의 크기에 영향을 받지 않는다.

행렬의 곱 : $ A = [a_{ij}]_{m*p} $ 과 $ B = [b_{ij}]_{p*n} $ 의 곱인 행렬 $ AB = [c_{ik}]_{m*n} $ 이다.
 - $ c_{ik} = a_{i1}b_{1k} + a_{i2}b_{2k} + ... + a_{ip}b_{pk} = \sum_{j=1}^{p} a_{ij}b{jk} $
 - 행렬 A와 행렬 B의 곱 AB는 A의 열의 개수, B의 행의 개수가 동일해야만 정의된다.
 - 행렬의 곱은 교환법칙이 성립하지 않는다 $AB \neq BA$


In [17]:
matrix_A = np.array([[1, 2, 3],
                     [3, 4, 6]])

matrix_B = np.array([[2, 4, 6],
                     [8, 1, 4]])

matrix_N = np.array([[2, 1],
                     [8, 3]])

matrix_M = np.array([[2, 1, 5],
                     [8, 3, 2],
                     [1, 0, 3]])

matrix_P = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

k = 10

# 행렬의 합
print(matrix_A + matrix_B)
# 행렬의 곱
print(matrix_A - matrix_B)
# 행렬의 스칼라배
print(k*matrix_A)
print(k*matrix_B)
print(k*matrix_N)
# 행렬의 곱, numpy.dot으로 행렬 곱을 수행할 수 있다
print(np.dot(matrix_A, matrix_M))
print(np.dot(matrix_B, matrix_M))

# 행렬의 곱에서는 교환법칙이 성립되지않는다
print(np.dot(matrix_M, matrix_P) == np.dot(matrix_P, matrix_M))


[[ 3  6  9]
 [11  5 10]]
[[-1 -2 -3]
 [-5  3  2]]
[[10 20 30]
 [30 40 60]]
[[20 40 60]
 [80 10 40]]
[[20 10]
 [80 30]]
[[21  7 18]
 [44 15 41]]
[[42 14 36]
 [28 11 54]]
[[False False False]
 [False False False]
 [False False False]]


In [6]:
# 사이즈가 다른 행렬은 더할 수 없다
print(matrix_N + matrix_B)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [7]:
# 사이즈가 다른 행렬은 뺄 수 없다
print(matrix_N - matrix_B)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [15]:
# A행렬의 행과, B행렬의 열 사이즈가 같지않으면 연산을 진행할 수 없다
print(np.dot(matrix_N, matrix_M))

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

행렬의 거듭 제곱 : n*n 행렬 A(n차 정방행렬 A)에 대해 $A^k$는 A를 k번 거듭제곱한 것을 나타낸다.
 - $ A^0 = I $
 - $ (A^b)^c = A^{bc} $
 - $ A^bA^c = A^{b+c} $

행렬 연산의 기본 성질
 1. $A + 0 = 0 + A = A$
 2. $IA = AI = A$
 3. $A + B = B + A$
 4. $(A+B)+C = A+(B+C)$
 5. $(AB)C = A(BC)$
 6. $A(B+C) = AB + AC$
 7. $(A+B)C = AC + AB$
 8. $a(B+C) = aB + aC$
 9. $(a+b)C = aC + bC$
 10. $(ab)C = a(bC)$
 11. $a(BC) = (aB)C = B(aC)$

행렬곱 소거법칙 적용 불가 : 행렬 A, B, C에 대해 AB = AC라고해서 반드시 B = C는 아니다  
AB = 0인 행렬 : AB = 0 일 때 일반적으로 A = 0 or B = 0이라고 할 수 없다

In [54]:
matrix_A = np.array([[1, 2],
                     [3, 4]])

matrix_B = np.array([[5, 6],
                     [7, 8]])

matrix_C = np.array([[7, 3],
                     [2, 4]])

scalar_a, scalar_b = 2, 3

matrix_I = np.array([[1, 0],
                     [0, 1]])

matrix_O = np.array([[0, 0],
                     [0, 0]])

In [55]:

# 거듭제곱
print(np.dot(matrix_A, matrix_A))
# np.linalg.matrix_power 를 사용하면 거듭제곱을 사용할 수 있다
print(np.linalg.matrix_power(matrix_A, 2))
# 이렇게 하면 그냥 각각의 원소값만 제곱이되어 나온다
print(matrix_A**2)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]


In [49]:
# 1번
print((matrix_A + matrix_O) == (matrix_O + matrix_A))
print((matrix_A + matrix_O) == matrix_A)
print((matrix_O + matrix_A) == matrix_A)

# 2번
print(np.dot(matrix_A, matrix_I) == np.dot(matrix_I, matrix_A))

# 3번
print((matrix_A + matrix_B) == (matrix_B + matrix_A))

# 4번
print((matrix_A + matrix_B) + matrix_C == matrix_A + (matrix_B + matrix_C))

# 5번
print(np.dot(np.dot(matrix_A, matrix_B), matrix_C) == np.dot(matrix_A, np.dot(matrix_B, matrix_C)))

# 6번
print(np.dot(matrix_A, (matrix_B + matrix_C)) == np.dot(matrix_A, matrix_B) + np.dot(matrix_A, matrix_C))

# 7번
print(np.dot((matrix_A + matrix_B), matrix_C) == np.dot(matrix_A, matrix_C) + np.dot(matrix_B, matrix_C))

# 8번
print(scalar_a*(matrix_B + matrix_C) == scalar_a*matrix_B + scalar_a*matrix_C)

# 9번
print((scalar_a + scalar_b)*matrix_C == scalar_a*matrix_C + scalar_b*matrix_C)

# 10번
print((scalar_a*scalar_b)*matrix_C == scalar_a*(scalar_b*matrix_C))

# 11번
print((scalar_a*(np.dot(matrix_B, matrix_C)) == np.dot(scalar_a*matrix_B, matrix_C)))
print(np.dot(scalar_a*matrix_B, matrix_C) == np.dot(matrix_B, scalar_a*matrix_C))
print((scalar_a*(np.dot(matrix_B, matrix_C)) == np.dot(matrix_B, scalar_a*matrix_C)))

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


In [52]:
matrix_A = np.array([[1, 0],
                     [0, 0]])

matrix_B = np.array([[1, 2],
                     [0, 1]])

matrix_C = np.array([[1, 2],
                     [0, 0]])

# AB == BA 이지만, A는 B와 같지 않다
print(np.dot(matrix_A, matrix_B) == np.dot(matrix_A, matrix_C))
print(matrix_B == matrix_C)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True False]]
