역행렬 : A의 역행렬은 $A^{-1}$ 로 표현하고, A inverse 라고 함
 - $AB = BA = I_n$
 - $AA^{-1} = A^{-1}A = I_n$

가역행렬 : 역행렬이 존재하는 행렬  
 - n차 정방행렬 A가 가역이면, A의 역행렬은 유일성이 보장된다  

비가역행렬 : 역행렬이 존재하지 않는 행렬   
 - 역행렬이 존재하지 않는경우는 특이한경우라 특이행렬 이라고도 함

2*2 역행렬 : 행렬 A에 대해 $ad - cb \neq 0 $ 이면 역행렬이 존재한다
 - $A^{-1} = \frac{1}{ad-bc} \begin{pmatrix} d & -b \\ -c & a \end{pmatrix} $

역행렬의 성질
 1. $A^{-1}$ 은 가역이고, $ (A^{-1})^{-1} = A $ 다
 2. $AB$ 는 가역이고, $ (AB)^{-1} = B^{-1}A^{-1} $ 다
 3. $\alpha A $는 가역이고, $ (\alpha A)^{-1} = \frac{1}{\alpha} A^{-1} $ 다
 4. $A^k$는 가역이고, $ (A^{-1})^k = (A^{k})^{-1} $ 다



In [1]:
import numpy as np

In [21]:
matrix_A = np.array([[1, 3], 
                     [5, 7]], dtype=np.float32)
matrix_B = np.array([[1, 2], 
                     [3, 4]], dtype=np.float32)
matrix_C = np.array([[1, 2], 
                     [2, 4]], dtype=np.float32)

scalar_a = 2

# numpy.linalg.inv를 통해 역행렬을 구할 수 있다
print(np.linalg.inv(matrix_A))
print(np.linalg.inv(matrix_B))


[[-0.875  0.375]
 [ 0.625 -0.125]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# ad - bc = 0인경우 역행렬을 구할 수 없다
print(np.linalg.inv(matrix_C))

LinAlgError: Singular matrix

In [23]:
# 1번
print(np.linalg.inv(np.linalg.inv(matrix_A)) == matrix_A)

# 2번
print(np.linalg.inv(np.dot(matrix_A, matrix_B)) == np.dot(np.linalg.inv(matrix_B), np.linalg.inv(matrix_A)))

# 3번
print(np.linalg.inv(scalar_a*matrix_A) == np.linalg.inv(matrix_A)/scalar_a)

# 4번 
scalar_k = 3
print(np.linalg.matrix_power(np.linalg.inv(matrix_A), scalar_k) == np.linalg.inv(np.linalg.matrix_power(matrix_A, scalar_k)))


[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


전치행렬 : A Transpose라고 부르며, 행렬 A의 열과 행을 바꿔놓은 행렬이다
 - $ A^T = [\acute{a}_{ij}]_{n*m} $ 의 성분 $\acute{a}_{ij}$ 는 A의 $a_{ji}$와 같다

전치행렬의 성질
 1. $(A^T)^T = A$
 2. $(A+B)^T = A^T + B^T$
 3. $(AB)^T = B^TA^T$
 4. $(\alpha A)^T = \alpha A^T$
 5. A가 가역이면, $(A^T)^{-1} = (A^{-1})^T$

In [35]:
matrix_A = np.array([[1, 3], 
                     [5, 7]], dtype=np.float32)

matrix_B = np.array([[1, 2], 
                     [3, 4]])

matrix_C = np.array([[1, 2, 3], 
                     [4, 5, 6]])

# matrix.T를 통해 Transpose를 할 수 있다.
print(matrix_A)
print(matrix_A.T)
print(matrix_C)
print(matrix_C.T)


[[1. 3.]
 [5. 7.]]
[[1. 5.]
 [3. 7.]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [36]:
# 1번
print((matrix_A.T).T == matrix_A)

# 2번
print((matrix_A+ matrix_B).T == matrix_A.T + matrix_B.T)

# 3번
print(np.dot(matrix_A, matrix_B).T == np.dot(matrix_B.T, matrix_A.T))

# 4번
print((scalar_a*matrix_A).T == scalar_a*matrix_A.T)

# 5번
print(np.linalg.inv(matrix_A.T) == np.linalg.inv(matrix_A).T)

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


대칭행렬 : 정방행렬 $A$가 전치행렬 $A^T$와 같으면 $(A = A^T)$라 한다  
 - $ A = [a_{ij}]_{m*n} $에서 주대각 성분을 기준으로 대칭되는 위치에 있는 성분이 같은 값 $a_{ij} = a_{ji}$
반대칭행렬 : $(-A = A^T)$를 만족하면 반대칭행렬이라 한다
 - $ B = [b_{ij}]_{m*n} $에서 주대각 성분을 기준으로 대칭되는 위치에 있는 성분이 절대값이 같고 부호는 다른 값 $b_{ij} = -b_{ji}$
 - 반대칭행렬의 주대각 성분은 모두 0이어야 한다 $b_{ii} = 0$

정방행렬과 전치행렬의 합과 차
 1. $(A + A^T)$ = 대칭행렬, $(A - A^T)$ = 반대칭행렬
 2. $A = \frac{1}{2} (A+A^T) + \frac{1}{2} (A-A^T)$
    - 정방행렬 A는 대칭행렬과 반대칭행렬의 합으로 나타낼 수 있다

대각행렬 : 주대각성분 이외의 모든 성분이 0인 정방행렬 $diag(a_{11}, ..., a_{nn})$으로 표시한다  
대각행렬의 곱 : 서로 크기가 같은 대각행렬 A, B의 곱은 $AB = diag(a_{11}b_{11}, ..., a_{nn}b_{nn})$이며 대각행렬의 곱도 대각행렬이다
 - m차 대각행렬 $D_m$을 행렬 A앞에 곱하면, A의 각 행에 그에 대응하는 $D_m$의 주대각 성분이 곱해진다
 - m차 대각행렬 $D_m$을 행렬 A뒤에 곱하면, A의 각 열에 그에 대응하는 $D_m$의 주대각 성분이 곱해진다

대각합 : 정방행렬 $A = [a_{ij}]_{n*m}$의 대각합 $tr(A)$는 주대각 성분의 합이다
 - $tr(A) = a_{11} + a_{22} + ... + a_{nn}$

대각합의 성질
 1. $tr(A + B) = tr(A) + tr(B)$
 2. $tr(cA) = c * tr(A)$
 3. $tr(AB) = tr(BA)$
 4. $tr(ABC) = tr(CAB) = tr(BCA)$ 순서가 유지되어야함

In [41]:
# 대칭 행렬
matrix_A = np.array([[1, 2, 3],
                     [2, 4, 5],
                     [3, 5, 6]])
# 반대칭 행렬
matrix_B = np.array([[0, 2, 3],
                     [-2, 0, 5],
                     [-3, -5, 0]])

# 대각 행렬
matrix_D = np.array([[2, 0, 0],
                     [0, 3, 0],
                     [0, 0, 4]])


print(matrix_A == matrix_A.T)
print(matrix_B == -matrix_B.T)
print(matrix_A == (matrix_A + matrix_A.T)/2 + (matrix_A - matrix_A.T)/2)

# 대각행렬을 뒤에 곱하면 각 행에 주대각 성분이 곱해진다
print(np.dot(matrix_D, matrix_A))
# 대각행렬을 앞에 곱하면 각 열에 주대각 성분이 곱해진다
print(np.dot(matrix_A, matrix_D))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ 2  6 12]
 [ 4 12 20]
 [ 6 15 24]]
[[ 2  4  6]
 [ 6 12 15]
 [12 20 24]]


In [77]:
def total(matrix):
    sum = 0

    for i in range(len(matrix)):
        sum += matrix[i][i]

    return sum

# 대각 행렬
matrix_D1 = np.array([[1, 2, 3],
                      [3, 2, 1],
                      [2, 1, 3]], dtype = np.float32)

matrix_D2 = np.array([[2, 4, 3],
                      [4, 3, 2],
                      [3, 2, 4]], dtype = np.float32)

matrix_D3 = np.array([[3, 5, 4],
                      [5, 4, 3],
                      [2, 4, 5]], dtype = np.float32)

scalar_d = 2

# 1번
print(total(matrix_D1 + matrix_D2) == total(matrix_D1) + total(matrix_D2))

# 2번
print(total(scalar_d * matrix_D1) == scalar_d * total(matrix_D1))

# 3번
print(total(np.dot(matrix_D1, matrix_D2)) == total(np.dot(matrix_D2, matrix_D1)))

# 4번
print(total(np.dot(np.dot(matrix_D1, matrix_D2), matrix_D3)) == total(np.dot(matrix_D3, np.dot(matrix_D1, matrix_D2))))
print(total(np.dot(matrix_D3, np.dot(matrix_D1, matrix_D2))) == total(np.dot(np.dot(matrix_D2, matrix_D3), matrix_D1)))

True
True
True
True
True


상삼각행렬 : 주대각성분의 아래쪽 모든 성분이 0인 정방행렬  
하삼각행렬 : 주대각성분의 위쪽 모든 성분이 0인 정방행렬  
삼각행렬의 곱 : 상삼각행렬 * 상삼각행렬 = 상삼각행렬 || 하삼각행렬 * 하삼각행렬 = 하삼각행렬
블록행렬 : 행렬의 특정행과 열사이를 경계로 나눠 부분행렬로 표현한 것

In [79]:
# 상삼각행렬
matrix_U = np.array([[1, 2, 3],
                     [0, 4, 5],
                     [0, 0, 6]])
# 하삼각행렬
matrix_L = np.array([[1, 0, 0],
                     [4, 2, 0],
                     [5, 6, 3]])

print(np.linalg.matrix_power(matrix_U, 2))
print(np.linalg.matrix_power(matrix_L, 2))

[[ 1 10 31]
 [ 0 16 50]
 [ 0  0 36]]
[[ 1  0  0]
 [12  4  0]
 [44 30  9]]


텐서 : 벡터와 행렬의 개념을 확장한 것, Rank에 따라 배열의 형태를 띄는 것
 - Rank n인 텐서는 Rank n-1인 텐서들의 배열 